### ISSUE TITLE
[Request] Forge Webui-compatible fork

### ISSUE THREAD

**Issue by PseudoChmod** [Seshelle/CFG_Rescale_webui#15]
I've installed this extension in my [forge webui](https://github.com/lllyasviel/stable-diffusion-webui-forge) and have noticed that it has no effect no matter what I set it to. Since the forge UI is a dramatic improvement over Automatic1111, people have begun migrating to it and it would be great to have this extension ported for us to use.

**Comment by troodpart** [comment]
Pretty sure the "LatentModifier" built in addon includes this function. Look for "Rescale Cfg Phi." Just be careful because it can go well beyond a value of 1.0 which really messes with results. 
If you still have A111 installed post an image with CFG rescale and I'll try to recreate it with Forge.

**Comment by PseudoChmod** [comment]
Sorry for missing this, I discovered latent phi recently and just tried this extension again with a reinstall and it seems to be working. Since there were no updates (for this extension) and several other extensions seem to have been fixed I must have had an corrupted installation. Sorry for the wild goose chase, closing.
