### ISSUE TITLE
[Feature request] Bring over CFG rescale setting from PNG info tab

### ISSUE THREAD

**Issue by jamesjimmy88** [Seshelle/CFG_Rescale_webui#3]
As per title. Using the PNG info tab will show the CFG rescale value, but using the _Send to_ buttons doesn't bring it over. It would be nice if it did (assuming it's possible).

**Comment by Kadah** [comment]
https://github.com/Seshelle/CFG_Rescale_webui/pull/2 should have resolved that, you may not have pulled the update.

**Comment by jamesjimmy88** [comment]
I updated everything and reset my ui-config.json; it's working now. Thank you!
