### ISSUE TITLE
[Bug] When "Show grid results for web" is disabled, the first image will not be color corrected

### ISSUE THREAD

**Issue by Fredbob396** [Seshelle/CFG_Rescale_webui#5]
Steps to reproduce:
1. Disable "Show grid in results for web" in Settings
2. Enable Auto Color Fix
3. Set batch size to 2 and click Generate
4. Notice that 3 results are returned. The first seed will not have a color-corrected equivalent
![bugexample1](https://github.com/Seshelle/CFG_Rescale_webui/assets/16653524/422ccc29-4630-4bc7-9401-ffba38b9a3fe)

**Comment by Seshelle** [comment]
Attempted a fix for this in the most recent commit. Leaving this open for a little while in case the issue persists in other setups.

**Comment by Seshelle** [comment]
After more testing, it appears to be resolved.
